name: Render

on:
  push:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          wget -O font.zip https://github.com/alerque/libertinus/releases/download/v7.051/Libertinus-7.051.zip
          unzip font.zip -d ./libertinus

      - uses: typst-community/setup-typst@v4
      - run: |
          $ErrorActionPreference = 'Stop'

          $root = (Get-Location).Path
          $renderDir = Join-Path $root 'render'

          New-Item -ItemType Directory -Force -Path $renderDir | Out-Null

          $typFiles = Get-ChildItem -Path $root -Recurse -File -Filter 'main.typ'

          foreach ($file in $typFiles) {
            $projectDir = Split-Path -Parent $file.FullName
            $projectName = Split-Path -Leaf $projectDir
            $renderPdf = Join-Path $renderDir ("$projectName.pdf")

            Write-Host "Compiling $($file.FullName) -> $renderPdf"
            typst compile --root $root --font-path ./libertinus/Libertinus-7.051/static/TTF/ $file $renderPdf
          }
        shell: pwsh

      - name: Release to main
        uses: softprops/action-gh-release@v2
        with:
          files: render/*.pdf
          tag_name: ${{ github.ref_name }}
